"""Fixed probe-corpus loading and batch construction for the cheap-tier
metrics (cross-loop-step overlap, repetition-stratified loss).

## Corpus artifact

`src/data/artifacts/corpus/pile10k_d4_b40_s512.json` is a byte-identical copy
of the same file from the earlier diagnostics code base
(verified byte-identical at copy time) -- 40 documents, 10 domains (4 docs
each, domain-balanced), generated by `scripts/data/prepare_corpus.py`
from `NeelNanda/pile-10k`. **Do not regenerate this file** -- the probe
corpus must stay fixed for the entire training run or cross-checkpoint
comparability is lost. This project reuses the
already-generated artifact rather than re-running the generator (which
needs network access to the HF Hub; this repo's runtime, notably on a
training cluster, should not need it).

## Why `real_text_batch`'s logic is reimplemented here, not vendored verbatim

The earlier code base's `collect/corpus.py::real_text_batch` implements exactly the batch
contract this module needs (real text only, B mutually distinct documents,
no padding -- raise instead, provenance metadata with `input_ids_sha8`). It
is NOT byte-for-byte vendored into `_vendored_loopdiag/` like `moe.py` /
`looped.py` / `text_repetition.py`, because it is not self-contained: its
only external dependency is that code base's `collect.schema.sha8`, and pulling
in the whole `schema.py` module to satisfy one import would mean vendoring
`TraceMeta`/`TraceGroup` dataclass machinery this project has no use for
(the collection-layer contract for offline diagnostic traces, not a metric
definition) -- adding entities without necessity, which vendoring is meant to
avoid. `sha8` itself IS vendored separately (see
`_vendored_loopdiag/sha8.py`) since it is small and self-contained.

`build_probe_batch` below reproduces `real_text_batch`'s logic line-for-line
(same constraints, same failure modes, same `token_source` field names) so
that a `probe_metrics.jsonl` row's `input_ids_sha8` means exactly what it
would mean if this module were that `collect.corpus` module itself. Any
future divergence between the two must be treated as a bug, not a design
choice -- if the original `real_text_batch` changes, this function should
be re-checked against it.
"""

from __future__ import annotations

from src.eval.probes.artifact_paths import named_checkpoint

import json
import random
from pathlib import Path
from typing import Any

import torch
from torch import Tensor

from src.metrics._vendored_loopdiag.sha8 import sha8
from src.metrics._vendored_loopdiag.text_repetition import bigram_repeat_rate

DEFAULT_CORPUS_PATH = (
    Path(__file__).resolve().parent / "artifacts" / "corpus" / "pile10k_d4_b40_s512.json"
)

CORPUS_ID = "pile10k_d4_b40_s512_drop1_v2"
"""Stable identifier for `DEFAULT_CORPUS_PATH`'s current contents, for
producers (e.g. `src/posttrain/guardrail_eval.py`) that must record
*which* frozen probe corpus a reading came from (the probe corpus version is
frozen; changing it would invalidate comparisons across checkpoints; recorded as
`sample.corpus_id` in `guardrail_eval.v1.jsonl`).

This is a naming/versioning discipline, not a new artifact: the corpus file
itself is unchanged (see module docstring -- "Do not regenerate this
file"). If the corpus content ever needs to change, that requires a NEW
file (e.g. `pile10k_d4_b40_s512_v2.json`) and a new constant here -- the
old file and this constant stay untouched so historical readings remain
reproducible against the corpus that actually produced them."""


LARGE_CORPUS_PATH = (
    Path(__file__).resolve().parent / "artifacts" / "corpus" / "pile10k_d50_b500_s512.json"
)
"""500-document probe corpus: same 10-domain-balanced
design as `DEFAULT_CORPUS_PATH` (`pile10k_d4_b40_s512.json`, 40 docs) but 50
docs/domain instead of 4, generated the same way by
`scripts/data/prepare_corpus.py` from `NeelNanda/pile-10k`. ONE domain differs:
`Books3` (used by the 40-doc corpus) has only 9 documents in `NeelNanda/
pile-10k` at this generator's `min_chars=4096` threshold -- nowhere near the
50 needed -- so `Wikipedia (en)` is substituted
(779 documents at the same threshold) rather than lower the per-domain count
or shrink the domain set. See `artifacts/corpus/README.md` for the full
domain-list diff, the exact generation command, and per-domain counts.

**This is a NEW, separate corpus, not a replacement** -- `DEFAULT_CORPUS_PATH`
/ `CORPUS_ID` above are untouched so every existing reading against the
40-doc corpus stays reproducible. Which corpus a given driver/probe uses is
decided by the driver code; this module only exposes the path + id, same
shape as the existing pair."""

LARGE_CORPUS_ID = "pile10k_d50_b500_s512_v1"
"""Stable identifier for `LARGE_CORPUS_PATH`'s current contents -- same
naming/versioning discipline as `CORPUS_ID` (see its docstring): the corpus
file is meant to stay fixed once frozen; a future content change requires a
new file + a new constant here, not an in-place edit of this one."""


LARGE_CORPUS_SMOLLM2_PATH = (
    Path(__file__).resolve().parent / "artifacts" / "corpus" / "pile10k_d50_b500_s512.smollm2_v2.json"
)
"""SmolLM2-tokenized frozen snapshot of `LARGE_CORPUS_PATH`. Produced by
`src.data.retokenize_probe_corpus.retokenize_corpus` against the real bundled
tokenizer in `artifacts/tokenizer/smollm2/` (see that directory's
`PROVENANCE.md` for its identity: HF repo, revision
`effd688a12921b4cc83e3312b6feb579f70f9c71`, per-file sha256) -- same 500
documents (text/domain/provenance fields byte-identical to `LARGE_CORPUS_PATH`,
verified by `retokenize_corpus`'s own field-preservation check), each with a
`token_ids`/`num_tokens` field added: text tokens + ONE trailing `<|endoftext|>`
(id 0), NO leading one -- SmolLM2's bos_id and eos_id are the SAME id, and a
document gets exactly one separator, at the end, not one at each end. Every document tokenizes to >= 512 tokens with this
tokenizer too (measured min 763, max 75,088 across the 500 docs, one fewer than
before per doc since there's one fewer separator) -- the probe-corpus token-count
floor holds regardless of which of the two tokenizers reads it.

**This is v2.** v1 (`pile10k_d50_b500_s512.smollm2.json`, id
`pile10k_d50_b500_s512_smollm2_v1`) put the shared bos/eos id at BOTH ends of every
document (two separators instead of one) -- a real bug in the ORIGINAL
`_NamedBpeTokenizer.encode_document`/`retokenize_probe_corpus._encode_document`
(both fixed alongside this regeneration: the framing now branches on
`bos_id == eos_id`, not just "does the tokenizer have both"). v1's file is left on
disk (not deleted, matching this project's no-silent-delete discipline) but no
longer referenced by any constant here -- nothing shipped that depended on it, so
there is no compatibility reason to keep exporting its id/path.

`LARGE_CORPUS_PATH` (the raw-text version) is UNCHANGED by this -- this is a
separate, additional frozen artifact, not a replacement; a caller that only has a
generic HF-style tokenizer can still tokenize `LARGE_CORPUS_PATH`'s raw text on the
fly (as `build_probe_batch` already does) instead of using this frozen snapshot."""

#: NO sha256 is quoted in the docstrings above, deliberately. This file's hash was
#: pinned there and was wrong: the sentence called it the tokenizer's hash while the
#: value was the corpus file's. Nothing caught it, because a hash written in prose
#: takes part in no lookup -- the only thing that can disagree with it is a reader.
#: Content identity is resolved at run time from `REGISTERED_CORPORA` below, where
#: being registered is what makes a corpus resolvable.

LARGE_CORPUS_SMOLLM2_ID = "pile10k_d50_b500_s512_smollm2_v2"
"""Stable identifier for `LARGE_CORPUS_SMOLLM2_PATH`'s current contents -- same
naming/versioning discipline as `CORPUS_ID`/`LARGE_CORPUS_ID`: a future content
change (e.g. a different SmolLM2 revision, or another framing correction) requires
a new file + a new constant here, not an in-place edit of this one."""


LARGE_CORPUS_B_PATH = (
    Path(__file__).resolve().parent / "artifacts" / "corpus" / "pile10k_B_d50_b500_s512.json"
)
""""Corpus B" for the expert-masking evaluation: a probe corpus disjoint from `LARGE_CORPUS_PATH` ("corpus A") by document sha256,
generated the same way (same dataset, same domain whitelist, same `min_chars=4096`,
same deterministic index-order selection) plus one addition -- documents already
picked by corpus A are excluded, so this collects the next eligible documents per
domain after corpus A's picks.

**485 documents, not 500.** Two of the 10 domains (`ArXiv`: 86 qualifying documents
total; `DM Mathematics`: 99) do not have enough remaining documents after excluding
corpus A's 50/domain to also supply a full 50 for corpus B (36 and 49 respectively);
every other domain does. Decision: keep the 485 documents
as-is rather than lower `min_chars` or break the 50/domain balance by pulling extra
documents from other domains -- see `artifacts/corpus/README.md`'s "Why 485, not 500"
section for the full per-domain counts and rationale (in short: matching domain
composition between A and B matters more than exact document-count equality, and a
~3% size difference is far smaller than the effect this evaluation is designed to
detect).

**This is a NEW, separate corpus, not a replacement** for anything -- same discipline
as `LARGE_CORPUS_PATH` above."""

LARGE_CORPUS_B_ID = "pile10k_B_d50_b500_s512_v1"
"""Stable identifier for `LARGE_CORPUS_B_PATH`'s current contents -- same
naming/versioning discipline as `LARGE_CORPUS_ID`."""


LARGE_CORPUS_B_SMOLLM2_PATH = (
    Path(__file__).resolve().parent / "artifacts" / "corpus"
    / "pile10k_B_d50_b500_s512.smollm2_v2.json"
)
"""SmolLM2-tokenized frozen snapshot of `LARGE_CORPUS_B_PATH`, produced by
`src.data.retokenize_probe_corpus.retokenize_corpus` against the same bundled
tokenizer as `LARGE_CORPUS_SMOLLM2_PATH` (`artifacts/tokenizer/smollm2/`) --
same 485 documents (text/domain/provenance fields byte-identical to
`LARGE_CORPUS_B_PATH`), each with a `token_ids`/`num_tokens` field added, same
"one trailing separator, no leading one" framing as corpus A's smollm2 snapshot
(SmolLM2's bos_id and eos_id are the same id). Every document tokenizes to
>= 512 tokens (measured min 754, max 45,782)."""

LARGE_CORPUS_B_SMOLLM2_ID = "pile10k_B_d50_b500_s512_smollm2_v2"
"""Stable identifier for `LARGE_CORPUS_B_SMOLLM2_PATH`'s current contents -- same
naming/versioning discipline as `LARGE_CORPUS_SMOLLM2_ID`."""


#: Every probe corpus this repo ships, as `(path, id)`. THE registry: being listed
#: here is what makes a corpus resolvable, so adding one is a single edit.
#:
#: `artifact_paths._corpus_id_from_content` derives its content-hash lookup from
#: this tuple rather than keeping a second list. It used to keep its own, and
#: `LARGE_CORPUS_SMOLLM2_PATH` was added here but not there -- so probing that
#: corpus raised `no registered corpus has content hash ...` at artifact-write
#: time. One fact, two places, nothing binding them: the two drifted the first
#: time a corpus was added.
#:
#: Hashes are NOT stored. They are computed from the files at lookup time, so a
#: corpus file that legitimately changes (a provenance fix, say) needs no edit

PROBE_BATCH = 40
"""Documents in the default probe batch -- every document of
`pile10k_d4_b40_s512.json`, and the `b40` in its name and id.

The other half of that corpus's identity, alongside `PROBE_SEQ`; both live with
the corpora they describe rather than in a driver.
"""

PROBE_SEQ = 512
"""Tokens per document window, BEFORE the corpus layer excludes one position.

Half of a corpus's identity: it is the `s512` in every corpus filename and id,
and `tokens_per_doc` (511) is this minus the one excluded position. It lives
here with the corpora it describes rather than in a driver -- it was defined in
`offline_trajectory_probe`, so every other driver reached a corpus fact by
importing it from a driver. (That module is NOT retiring -- `guardrail_eval`
calls its `compute_trajectory_metrics` -- but a corpus constant still does not
belong to one of the drivers that reads it.)
"""

WEIGHTS_FILENAME = "pytorch_model.bin"
"""The weights file every checkpoint directory must contain, non-empty.

Not corpus identity, but it sat beside `PROBE_SEQ` in the retiring module and
has the same problem. `src.pretrain.checkpointing.store` does not export it: it
guarantees the manifest marker, not the weights filename convention.

Two other definitions of this string exist (`src/eval/run_eval.py`, and
`PROBE_SEQ` likewise in `adapters/run_hf_router_probe.py`). They are NOT
consolidated here -- that is a separate change with its own blast radius.
"""

#: here -- and a stored hash cannot silently disagree with the file it names.
REGISTERED_CORPORA = (
    (DEFAULT_CORPUS_PATH, CORPUS_ID),
    (LARGE_CORPUS_PATH, LARGE_CORPUS_ID),
    (LARGE_CORPUS_SMOLLM2_PATH, LARGE_CORPUS_SMOLLM2_ID),
    (LARGE_CORPUS_B_PATH, LARGE_CORPUS_B_ID),
    (LARGE_CORPUS_B_SMOLLM2_PATH, LARGE_CORPUS_B_SMOLLM2_ID),
)
#: ⚠️ A registered corpus travels with the CODE repository. The walk test over
#: this tuple fails -- it does not skip -- when a file is absent, so adding a
#: line here is adding a FILE to the code repo, not just a constant. Weigh the
#: size before registering a large corpus.


def load_corpus(path: str | Path = DEFAULT_CORPUS_PATH) -> tuple[list[dict], dict]:
    """Read the probe-corpus JSON, return `(docs, provenance)`.

    Mirrors the earlier code base's `collect.corpus.load_corpus` (same shape: a dict with
    `"docs"` and `"provenance"` keys, produced by `scripts/prepare_corpus.py`).
    """
    blob = json.loads(Path(path).read_text())
    if not isinstance(blob, dict) or "docs" not in blob:
        raise ValueError(
            f"{path} is not a prepare_corpus.py artifact (missing 'docs' key)."
        )
    return blob["docs"], blob.get("provenance", {})


#: The two exclusion rules, as the literal strings recorded in every artifact.
#: Defined HERE, once, and imported by everything that writes or checks them:
#: two spellings of one rule raise no error, they just split a single corpus
#: into two groups in any analysis that keys on the string.
RULE_POSITION_0 = "position_0"
"""Exclude window position 0 -- llama3's framing, and the uniform-length rule for
corpora that prefix nothing at all."""

RULE_POSITION_LAST = "position_last"
"""Exclude the last window position -- SmolLM2's framing (one trailing separator)."""

EXCLUSION_RULES = (RULE_POSITION_0, RULE_POSITION_LAST)

#: This project's own tokenizers, and the rule each one's framing implies. Open
#: models pass a rule directly -- none of them is llama3 or smollm2, and
#: recording "OLMoE, llama3" would read as a filled-in mistake rather than as
#: "exclude position 0".
RULE_BY_TOKENIZER = {"llama3": RULE_POSITION_0, "smollm2": RULE_POSITION_LAST}


def exclusion_rule_for_tokenizer(tokenizer_name: str) -> str:
    """The rule this project's `tokenizer_name` implies. Raises on an unknown name."""
    try:
        return RULE_BY_TOKENIZER[tokenizer_name]
    except KeyError:
        raise ValueError(
            f"unknown tokenizer_name {tokenizer_name!r}; known: "
            f"{sorted(RULE_BY_TOKENIZER)}. Refusing to guess: the wrong rule "
            "excludes the wrong end of every document and nothing fails."
        ) from None


def excluded_separator_position(exclusion_rule: str, seq: int) -> int:
    """Which WINDOW-RELATIVE position (0-based, within a length-`seq` window) `build_probe_batch`
    uniformly excludes from every document, given the framing rule in force.

    `exclusion_rule` is REQUIRED, no default -- which position holds the separator token
    depends entirely on which tokenizer's framing convention was used
    (`src.data.tokenizer._NamedBpeTokenizer.encode_document`), so guessing wrong here would
    silently drop a real content token and keep the separator, corrupting every downstream
    probe metric without an error (a live risk now that a second tokenizer with a DIFFERENT
    framing exists).

    Named for the RULE rather than the tokenizer: the parameter
    selects a framing, not an identity. The three open baselines are neither llama3
    nor smollm2, and two of them prefix nothing at all -- for those, `"position_0"`
    removes an ordinary content token to keep every document the same length, which
    is why their `special_tokens_excluded` reads 0.

    - `"position_0"`: position `0` -- Llama-3 documents are framed BOS + text + EOS, so the
      tokenizer's own `truncation=True` (keep-first-`seq`) ALWAYS keeps the prepended BOS at
      the very front of the window.
    - `"position_last"`: position `seq - 1` (the LAST slot) -- SmolLM2 documents are framed
      text + ONE trailing separator, no leading one, so there is nothing special at the
      front; the mirror-image convention (uniform LAST-position exclusion, for the same
      reason the llama3 case is uniform FIRST-position exclusion -- see
      `build_probe_batch`'s "why uniform rather than wherever a special token is" comment)
      keeps every document the same post-exclusion length regardless of seed.
    """
    if exclusion_rule == RULE_POSITION_0:
        return 0
    if exclusion_rule == RULE_POSITION_LAST:
        return seq - 1
    raise ValueError(
        f"unknown exclusion_rule {exclusion_rule!r}; choose from {list(EXCLUSION_RULES)}. "
        "A tokenizer name is not a rule: use exclusion_rule_for_tokenizer() for this "
        "project's models, and pass the rule directly for anything else."
    )


def build_probe_batch(
    tokenizer: Any,
    corpus_path: str | Path = DEFAULT_CORPUS_PATH,
    *,
    batch: int,
    seq: int,
    exclusion_rule: str,
    seed: int = 0,
) -> tuple[Tensor, dict]:
    """Tokenize the first `batch` corpus documents into `[batch, seq]` real-text
    token ids, returning `(input_ids, token_source)`.

    Every failure mode below raises rather than silently degrading -- padding,
    truncated batches, or repeated samples would each produce a shape-valid,
    numerically-plausible-looking tensor with a silently smaller effective
    sample size or corpus-polluting pad tokens (same rationale as
    the original `real_text_batch`'s docstring; see this
    module's docstring for why the logic is reimplemented rather than
    imported).

    Args:
        tokenizer: any HF-style tokenizer (`tokenizer(text, return_tensors="pt",
            truncation=True, max_length=seq)`).
        corpus_path: path to the probe-corpus JSON artifact.
        batch: number of documents to use (must be <= corpus size).
        seq: sequence length; documents tokenizing to fewer than `seq` tokens
            raise (no padding).
        exclusion_rule: REQUIRED, no default -- `"position_0"` or `"position_last"` (see
            `excluded_separator_position`). Says which window position holds the separator
            token that gets uniformly excluded from every document; the two tokenizers frame
            documents differently (BOS-at-front vs. separator-at-back), so this cannot be
            inferred safely from `tokenizer` alone (SmolLM2's framing differs from Llama-3's).
        seed: **0 (default) is byte-identical to this function's original
            behavior** -- every document's window is tokens `[0:seq]` (HF's
            own `truncation=True, max_length=seq`, keep-start). A nonzero
            seed instead draws, per document, a uniformly random
            `[start:start+seq]` window from that document's FULL
            tokenization (not padding, still real text, still no
            duplicates), via `random.Random(seed)` -- reproducible given the
            same seed, and DIFFERENT input content across different seeds.
            This is what lets a metric computed on top of a fixed probe
            batch (e.g. `src.eval.probes.offline_trajectory_probe`'s F3/F4,
            which otherwise have no source of run-to-run variance at all,
            unlike F1's `--repeats` random perturbation directions) build
            error bars across repeated measurements (F3/F4 on a single fixed
            probe corpus otherwise have no error bars across seeds; the
            PRIMARY base/era-1/era-2 three-point comparison always uses seed=0 --
            comparability across the three points requires identical
            input -- nonzero seeds are an ADDITIONAL error-bar layer on
            top, never the primary measurement).

    Returns:
        `input_ids`: `[batch, seq]` LongTensor.
        `token_source`: provenance dict, same field names as
            the original `real_text_batch`'s (`kind`,
            `corpus_file`, `corpus_file_sha256`, `corpus_provenance`,
            `tokenizer`, `batch`, `seq`, `n_tokens`, `docs`,
            `input_ids_sha8`) plus `seed` (new field, always present --
            explicit even when 0, same "explicit even when off" convention
            `src.pretrain.manifest`'s `autocast` field uses), so it can
            be dropped straight into a `checkpoint_manifest.json` or a
            `probe_metrics.jsonl` row without renaming.
    """
    excluded_col = excluded_separator_position(exclusion_rule, seq)  # raises on a bad rule

    docs, provenance = load_corpus(corpus_path)
    if len(docs) < batch:
        raise ValueError(
            f"corpus only has {len(docs)} docs, need {batch} mutually distinct ones."
        )
    docs = docs[:batch]

    # seed=0 keeps the EXACT original code path (tokenizer's own truncation)
    # rather than reimplementing "start=0" via the random-window branch below
    # -- this guarantees zero behavior change for every existing caller that
    # never passes `seed` (default-arg backward compatibility is a property
    # of the CODE PATH here, not just the default value).
    rng = random.Random(seed) if seed != 0 else None

    # Only used to COUNT what the uniform drop removed; the drop itself is
    # positional, so an empty set here changes nothing but the count.
    special_ids = set(getattr(tokenizer, "all_special_ids", None) or [])
    n_special_dropped = 0

    rows: list[Tensor] = []
    used: list[dict] = []
    for d in docs:
        if rng is None:
            enc = tokenizer(d["text"], return_tensors="pt", truncation=True, max_length=seq)
            n = int(enc["input_ids"].shape[1])
            if n < seq:
                raise ValueError(
                    f"doc {d['name']!r} tokenized to only {n} tokens, need seq={seq}. "
                    "No padding -- pad tokens would produce residual/router decisions at "
                    "meaningless positions and pollute token-aggregated metrics silently."
                )
            window = enc["input_ids"][:, :seq]
            start, doc_n_tokens = 0, None  # keep-start; full length not needed
        else:
            enc_full = tokenizer(d["text"], return_tensors="pt", truncation=False)
            n = int(enc_full["input_ids"].shape[1])
            if n < seq:
                raise ValueError(
                    f"doc {d['name']!r} tokenized to only {n} tokens, need seq={seq}. "
                    "No padding -- pad tokens would produce residual/router decisions at "
                    "meaningless positions and pollute token-aggregated metrics silently."
                )
            start = rng.randint(0, n - seq)  # inclusive both ends; n==seq -> start=0 always
            window = enc_full["input_ids"][:, start : start + seq]
            doc_n_tokens = n
        # Drop ONE uniform position of EVERY window (originally always position 0, since
        # only Llama-3 existed then). WHICH position is now `excluded_col`, decided once up
        # front by `tokenizer_name` via `excluded_separator_position` -- 0 for llama3 (BOS at
        # the front), `seq - 1` for smollm2 (its single separator is at the back). Done here, in the corpus layer, so every
        # consumer inherits it from one place: the four offline probes, guardrail_eval and
        # the open-source adapters all build their batch through this function, and a
        # per-driver drop would leave whichever consumer nobody remembered measuring a
        # different corpus.
        #
        # Why uniform rather than "wherever a special token is": only probe seed 0 carries a
        # start marker (its window is the tokenizer's own truncation), so a conditional drop
        # would leave seed 0's documents one token shorter than the others. Every document-
        # scoped operation downstream reshapes a flat matrix with ONE tokens_per_doc, and
        # equal length is also what makes "mean over all tokens" identical to "each document
        # weighted 1/40". Percentiles have no per-document-averaged definition at all, so the
        # ragged case would need a new definition of the reported quantity, not new code.
        dropped_id = int(window[0, excluded_col].item())
        dropped_is_special = dropped_id in special_ids
        n_special_dropped += int(dropped_is_special)
        if excluded_col == 0:
            window = window[:, 1:]
            kept_window_start = int(start) + 1  # first kept token is past the dropped one
        else:
            window = window[:, :excluded_col]
            kept_window_start = int(start)  # nothing chopped off the front this time
        rows.append(window)
        # `window_start` / `doc_n_tokens` are recorded so a caller concatenating
        # SEVERAL seeds can tell how much genuinely distinct text it ended up
        # with: different seeds draw different windows, but on a short document
        # those windows OVERLAP, and counting `batch * seq * n_seeds` would then
        # report a sample size that does not exist. Deduplicating needs the
        # position intervals, which only this function knows.
        # (Seeds 0/1/2 over these 40 docs yield 49,646 distinct tokens, not 61,440.)
        # `doc_n_tokens` is None on the seed=0 path, which uses the tokenizer's
        # own truncation and never materializes the full tokenization.
        # `window_start` is the position of the FIRST KEPT token -- past the dropped one when
        # the drop was at the front (llama3), unchanged when the drop was at the back
        # (smollm2, nothing shifts the front).
        used.append(
            {k: d[k] for k in ("name", "domain", "source_index", "sha256") if k in d}
            | {
                "window_start": kept_window_start,
                "window_len": int(seq) - 1,
                "doc_n_tokens": doc_n_tokens,
                "slots": int(seq) - 1,
                "dropped_token_is_special": bool(dropped_is_special),
                # Explicit fields -- `dropped_token_is_special`/
                # `first_token_dropped` (below) predate a second tokenizer existing and are
                # kept as-is; these two say
                # precisely WHAT was excluded without requiring the reader to already know
                # which tokenizer_name implies which position.
                "excluded_position": int(excluded_col),
                "excluded_token_id": dropped_id,
            }
        )

    input_ids = torch.cat(rows, dim=0)
    uniq = {tuple(r.tolist()) for r in input_ids}
    if len(uniq) != batch:
        raise ValueError(
            f"only {len(uniq)} of {batch} samples are mutually distinct -- duplicate "
            "samples would make the reported sample size a fiction."
        )

    corpus_path = Path(corpus_path)
    token_source = {
        "kind": "real_text",
        # Named root + relative path, never the absolute one. This field goes
        # into EVERY probe artifact, so an absolute path here put the account
        # name in every row produced by every driver -- and no static check
        # could see it, because the rows are written at run time under a
        # scratch directory. Found by the run-time guard.
        **named_checkpoint(corpus_path, field="corpus"),
        "corpus_file_sha256": _file_sha256(corpus_path),
        "corpus_provenance": provenance,
        # A LOCAL tokenizer's `name_or_path` is an absolute path, so recording
        # it verbatim put the account name in every artifact -- the same leak
        # as `corpus_file`, one field over. A hub id (no such directory) is
        # kept as-is: it identifies the tokenizer without naming a machine.
        **_named_tokenizer(getattr(tokenizer, "name_or_path", "unknown")),
        "batch": batch,
        "seq": seq,
        "seed": seed,
        # `n_tokens` counts what is actually returned, AFTER the drop -- a
        # nominal `batch * seq` here would overstate every downstream count by
        # one token per document.
        "n_tokens": batch * (seq - 1),
        "n_tokens_before_drop": batch * seq,
        "first_token_dropped": True,
        # Explicit fields (added with SmolLM2's framing): which
        # tokenizer's convention decided the exclusion, and at which uniform window position
        # -- `first_token_dropped` stays `True` (it's still accurate: exactly one token is
        # still uniformly excluded per window) but is misleadingly named for `smollm2`
        # (position seq-1, not 0) -- these two fields are what a renamed field would be
        # computed from.
        "exclusion_rule": exclusion_rule,
        "excluded_position": int(excluded_col),
        "special_tokens_excluded": int(n_special_dropped),
        "tokens_per_doc": seq - 1,
        "slots_per_document": [seq - 1] * batch,
        "docs": used,
        "input_ids_sha8": sha8(input_ids),
    }
    return input_ids, token_source


def _named_tokenizer(name_or_path: str) -> dict[str, str]:
    """`{"tokenizer": <hub id>}`, or the named-root split for a local directory."""
    if name_or_path and Path(name_or_path).exists():
        return {"tokenizer": Path(name_or_path).name,
                **named_checkpoint(name_or_path, field="tokenizer")}
    return {"tokenizer": name_or_path}


def _file_sha256(path: str | Path) -> str:
    import hashlib

    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_repeat_rate_buckets(
    tokenizer: Any,
    corpus_path: str | Path = DEFAULT_CORPUS_PATH,
    *,
    seq: int,
    n_buckets: int = 3,
) -> dict[str, Any]:
    """Precompute each probe document's `bigram_repeat_rate` (vendored,
    unmodified definition -- see `_vendored_loopdiag/text_repetition.py`) and
    assign it to one of `n_buckets` equal-count quantile buckets.

    Language-modelling loss is reported stratified by the probe corpus's repetition rate: this is a
    STATIC property of the fixed probe corpus (does not depend on the model
    or training step), so it is computed once (e.g. at training start) and
    cached -- the training loop's per-M-step probe forward looks up which
    bucket each document belongs to, it does not recompute
    `bigram_repeat_rate` every time.

    Buckets are computed on the SAME tokenization (same tokenizer, same
    `seq` truncation) that will be used for the actual probe forward passes
    -- `bigram_repeat_rate` operates on token ids, not characters/words (see
    the vendored module's docstring on why token-level vs word-level differ
    by >2x), so a mismatched tokenizer/seq here would silently bucket
    documents by the wrong repetition rate.

    Args:
        tokenizer: HF-style tokenizer, same one used for probe forwards.
        corpus_path: probe-corpus JSON artifact.
        seq: truncation length, must match the probe batch's `seq`.
        n_buckets: number of equal-count quantile buckets (default 3:
            low/mid/high).

    Returns:
        `{"n_buckets": n_buckets, "bucket_boundaries": [...], "docs":
        [{"name", "domain", "bigram_repeat_rate", "bucket"}], "seq": seq,
        "tokenizer": tokenizer.name_or_path}` -- serializable to JSON as-is,
        intended to be cached to `<corpus>.repeat_buckets.json` once per
        training run (not re-derived every probe step).
    """
    docs, _ = load_corpus(corpus_path)
    rates: list[tuple[dict, float]] = []
    for d in docs:
        enc = tokenizer(d["text"], truncation=True, max_length=seq)
        ids = enc["input_ids"]
        if len(ids) < seq:
            raise ValueError(
                f"doc {d['name']!r} tokenized to only {len(ids)} tokens, need seq={seq}."
            )
        rates.append((d, bigram_repeat_rate(ids[:seq])))

    rates.sort(key=lambda pair: pair[1])
    n = len(rates)
    bucket_size = -(-n // n_buckets)  # ceil division: last bucket may be smaller
    boundaries: list[float] = []
    out_docs: list[dict] = []
    for i, (d, rate) in enumerate(rates):
        bucket = min(i // bucket_size, n_buckets - 1)
        out_docs.append(
            {"name": d["name"], "domain": d["domain"], "bigram_repeat_rate": rate, "bucket": bucket}
        )
        if i % bucket_size == 0:
            boundaries.append(rate)

    return {
        "n_buckets": n_buckets,
        "bucket_boundaries": boundaries,
        "docs": out_docs,
        "seq": seq,
        # A LOCAL tokenizer's `name_or_path` is an absolute path, so recording
        # it verbatim put the account name in every artifact -- the same leak
        # as `corpus_file`, one field over. A hub id (no such directory) is
        # kept as-is: it identifies the tokenizer without naming a machine.
        **_named_tokenizer(getattr(tokenizer, "name_or_path", "unknown")),
    }
